/*
* generated by Xtext
*/
package org.xtext.petrinet.mydsl1.ui.contentassist;

import org.xtext.petrinet.mydsl1.ui.contentassist.AbstractMyDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {

}
