/*
* generated by Xtext
*/
package org.xtext.petrinet.mydsl1.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/petrinet/mydsl1/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
