/*
* generated by Xtext
*/
package org.xtext.petrinet.mydsl1.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MyDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
